#!/usr/bin/env python3
"""Generate figures-src/fig3.1_consort.drawio from the pipeline's own constants.

Figure 3.1 is drawn from eleven \\pc macros. A .drawio file cannot hold a macro,
so converting it means freezing those counts as literal text. This script does
that by READING generated/pipeline_constants.tex rather than by anyone typing
the numbers, so the frozen diagram provably matches the pipeline run that
produced it.

Re-run it after any pipeline run to refresh the frozen values:

    python3 figures-src/make_consort_drawio.py
"""
import io, os, re, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONST = os.path.join(ROOT, "generated", "pipeline_constants.tex")
OUT   = os.path.join(ROOT, "figures-src", "fig3.1_consort.drawio")

NEEDED = ["ConsortNTotal", "ConsortNExclNotFirst", "ConsortNFirstStay",
          "ConsortNExclLos", "ConsortNFinal",
          "NOnsetsA", "NOnsetsB", "NOnsetsC",
          "PctOnsetsA", "PctOnsetsB", "PctOnsetsC"]

def load():
    txt = io.open(CONST, encoding="utf-8").read()
    vals = {}
    for name in NEEDED:
        m = re.search(r"\\newcommand\{\\pc%s\}\{(.*)\}\s*$" % name, txt, re.M)
        if not m:
            raise SystemExit("macro \\pc%s not found in %s" % (name, CONST))
        v = m.group(1)
        v = re.sub(r"\\ensuremath\{(.*)\}$", r"\1", v.strip())
        v = v.replace("{,}", ",").replace("\\,", " ").strip()
        if not v:
            raise SystemExit("macro \\pc%s resolved to empty" % name)
        vals[name] = v
    return vals

BOX = ("rounded=1;arcSize=6;whiteSpace=wrap;html=1;fillColor=#ACF5BD;fillOpacity=20;"
       "strokeColor=#005B5E;strokeWidth=2;fontSize=20;fontFamily=Times New Roman;")
FINAL = ("rounded=1;arcSize=6;whiteSpace=wrap;html=1;fillColor=#005B5E;fillOpacity=15;"
         "strokeColor=#004244;strokeWidth=2;fontSize=20;fontFamily=Times New Roman;")
EXCL = ("rounded=1;arcSize=6;whiteSpace=wrap;html=1;fillColor=#FFE8D4;fillOpacity=40;"
        "strokeColor=#FF791E;strokeWidth=2;fontSize=20;fontFamily=Times New Roman;")
VAR = ("rounded=1;arcSize=6;whiteSpace=wrap;html=1;fillColor=#ACF5BD;fillOpacity=20;"
       "strokeColor=#005B5E;strokeWidth=2;fontSize=19;fontFamily=Times New Roman;")
ARR = "endArrow=block;html=1;strokeColor=#005B5E;strokeWidth=2;"
XAR = "endArrow=block;html=1;strokeColor=#FF791E;strokeWidth=2;"

def cell(i, v, style, x, y, w, h):
    return ('<mxCell id="%s" value="%s" style="%s" vertex="1" parent="1">'
            '<mxGeometry x="%d" y="%d" width="%d" height="%d" as="geometry" /></mxCell>'
            % (i, v, style, x, y, w, h))

def edge(i, s, t, style, extra=""):
    return ('<mxCell id="%s" style="%s%s" edge="1" parent="1" source="%s" target="%s">'
            '<mxGeometry relative="1" as="geometry" /></mxCell>' % (i, style, extra, s, t))

def main():
    v = load()
    c = [
      cell("total", "MIMIC-IV v3.1 ICU stays&lt;br&gt;n = %s" % v["ConsortNTotal"], BOX, 150, 40, 300, 56),
      cell("e1", "Non-first ICU stay&lt;br&gt;n = %s excluded" % v["ConsortNExclNotFirst"], EXCL, 520, 44, 220, 48),
      cell("first", "First ICU stay per patient&lt;br&gt;(all ages &amp;#8805; 18 in MIMIC-IV)&lt;br&gt;n = %s" % v["ConsortNFirstStay"], BOX, 150, 150, 300, 66),
      cell("e2", "LOS &amp;lt; 4 hours&lt;br&gt;n = %s excluded" % v["ConsortNExclLos"], EXCL, 520, 159, 220, 48),
      cell("final", "&lt;b&gt;Analysis cohort&lt;/b&gt;&lt;br&gt;n = %s" % v["ConsortNFinal"], FINAL, 150, 270, 300, 56),
      cell("va", "Variant A&lt;br&gt;Sepsis: %s&lt;br&gt;(%s%%)" % (v["NOnsetsA"], v["PctOnsetsA"]), VAR, 40, 390, 160, 62),
      cell("vb", "Variant B&lt;br&gt;Sepsis: %s&lt;br&gt;(%s%%)" % (v["NOnsetsB"], v["PctOnsetsB"]), VAR, 220, 390, 160, 62),
      cell("vc", "Variant C&lt;br&gt;Sepsis: %s&lt;br&gt;(%s%%)" % (v["NOnsetsC"], v["PctOnsetsC"]), VAR, 400, 390, 160, 62),
      edge("a1", "total", "first", ARR), edge("a2", "first", "final", ARR),
      edge("x1", "total", "e1", XAR), edge("x2", "first", "e2", XAR),
      edge("b1", "final", "va", ARR, "exitX=0.5;exitY=1;entryX=0.5;entryY=0;"),
      edge("b2", "final", "vb", ARR, "exitX=0.5;exitY=1;entryX=0.5;entryY=0;"),
      edge("b3", "final", "vc", ARR, "exitX=0.5;exitY=1;entryX=0.5;entryY=0;"),
    ]
    stamp = datetime.date.today().isoformat()
    xml = ('<!-- GENERATED by figures-src/make_consort_drawio.py from\n'
           '     generated/pipeline_constants.tex on %s.\n'
           '     The eleven cohort counts below are FROZEN copies of pipeline\n'
           '     macros. If the pipeline is re-run, re-run this script. -->\n'
           '<mxfile host="app.diagrams.net" type="device">\n'
           '  <diagram id="consort-flow" name="Figure 3.1 CONSORT flow">\n'
           '    <mxGraphModel dx="1100" dy="800" grid="1" gridSize="10" guides="1" tooltips="1"\n'
           '                  connect="1" arrows="1" fold="1" page="1" pageScale="1"\n'
           '                  pageWidth="800" pageHeight="500" math="0" shadow="0">\n'
           '      <root>\n        <mxCell id="0" /><mxCell id="1" parent="0" />\n        '
           % stamp) + "\n        ".join(c) + \
          '\n      </root>\n    </mxGraphModel>\n  </diagram>\n</mxfile>\n'
    io.open(OUT, "w", encoding="utf-8").write(xml)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    for k in NEEDED:
        print("  %-22s %s" % (k, v[k]))

def check():
    """Verify the frozen .drawio still matches the pipeline constants.

    The whole risk of converting Figure 3.1 is that its counts are frozen while
    the pipeline moves on. That risk is acceptable only if it is detectable, so
    this compares the two and fails loudly when they diverge.
    """
    if not os.path.exists(OUT):
        raise SystemExit("FAIL: %s does not exist; run without --check" % OUT)
    v = load()
    xml = io.open(OUT, encoding="utf-8").read()
    stale = [k for k in NEEDED if v[k] not in xml]
    if stale:
        raise SystemExit(
            "FAIL: fig3.1_consort.drawio is STALE against the pipeline.\n"
            "      Diverged: %s\n"
            "      The frozen diagram no longer matches generated/"
            "pipeline_constants.tex.\n"
            "      Re-run: python3 figures-src/make_consort_drawio.py"
            % ", ".join(stale))
    print("ok   fig3.1_consort.drawio matches the pipeline constants "
          "(%d values checked)" % len(NEEDED))

if __name__ == "__main__":
    if "--check" in sys.argv:
        check()
    else:
        main()
